{% set version = "1.9.0" %}

package:
  name: jupyter-releaser
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/j/jupyter-releaser/jupyter_releaser-{{ version }}.tar.gz
  sha256: 665f5981f3c67be177fbb790aad22c807a2272e801ec223796fcc3f9b1bf62db

build:
  number: 0
  noarch: python
  entry_points:
    - jupyter-releaser = jupyter_releaser.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling >=1.0
  run:
    - click
    - ghapi <=1.0.4
    - github-activity ~=0.2
    - pipx
    - importlib_resources
    - jsonschema >=3.0.1
    - mdformat
    - packaging
    - pkginfo
    - pypiserver
    - python >={{ python_min }}
    - requests
    - requests-cache
    - toml ~=0.10

test:
  imports:
    - jupyter_releaser
    - jupyter_releaser.actions
  commands:
    - jupyter-releaser --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://jupyter.org
  summary: Jupyter Releaser for Python and/or npm packages.
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/jupyter-server/jupyter_releaser

extra:
  recipe-maintainers:
    - krassowski
    - blink1073
    - jtpio
